### ISSUE TITLE
can't add vodafone SIM card to pybytes

### ISSUE THREAD

**Issue by ozembuch** [pycom/pycom-micropython-sigfox#566]
I order vodafone SIM card via pycom eshop. After adding Order number, it should add SIM card to pybytes. But even the message says SIM card was added, I do not see any SIM cards fro manage. Without this step I cant activate SIM card
![image](https://user-images.githubusercontent.com/49308406/134147575-88ddaf54-62b8-43e4-8efb-0054d79f1d68.png)

**Comment by elmasria** [comment]
Hi @ozembuch,

Thank you for reporting this, 

We are working with the third party (Vodafone) to fix this issue and will update Pybytes ASP. 

Have a nice day,

Best Regards,
Ahmad EL Masri

**Comment by razvandragomirescu** [comment]
I have the exact same issue and it is blocking us from using purchased SIMs, anxious to get this solved.

**Comment by ozembuch** [comment]
any updates?

**Comment by razvandragomirescu** [comment]
Is this fixable or should I ask for a refund? The cards are currently unusable since they are not activated and the clock is ticking, we've already lost 1 month out of the 12 we paid for.

**Comment by elmasria** [comment]
Hi All,

Thank you for being patient. We have fixed the issue.

Please try to read your project using the order number.

Note: the Count of the months will be count from the first day you activate your sim.

Let me know if you got any issues during adding/activating a sim under Pybytes

Best Regards,
Ahmad EL Masri

**Comment by razvandragomirescu** [comment]
It still does not work for me, see https://youtu.be/cKhy4SvRDVY . Am I doing something wrong? Thank you!

**Comment by elmasria** [comment]
@razvandragomirescu because you are not using the same email (under pybytes) that you purchased the sim with. if you would like to change the email please send us an email.

**Comment by razvandragomirescu** [comment]
It's exactly the same email I used when ordering, see attached order confirmation below and my email in the video. 
<img width="787" alt="orderconfirmation" src="https://user-images.githubusercontent.com/5519034/136988053-808d8fdb-f560-4864-b714-a3f049dc2500.png">

**Comment by razvandragomirescu** [comment]
Problem solved, it appears that I have entered another email when I _paid_ for the order, the account, the Vodafone contract and the confirmation were all on my @whispercash.com email but for some reason the Stripe payment shows up under my @gmail.com account. I was able to add the SIM cards by creating an account with my GMail address. Very confusing but I'm glad it worked.

**Comment by ozembuch** [comment]
it still does not work for me, same issue as before. The email for order and pybytes account is same. Am I missing something

**Comment by elmasria** [comment]
@ozembuch, 

Thank you for reporting this

To be able to get more details and check the status please send us the details of your account (order number, email address) to pybytes@pycom.io. 

Best Regards,
Ahmad El Masri
